# netlify.toml - Configuración para Netlify
# UBICACIÓN: raíz del proyecto (mismo nivel que backend/ y frontend/)

[build]
  base = "frontend"
  publish = "frontend/dist"
  command = " npm ci && npm run build"

# Configuración para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Variables de entorno para el build
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Configuración para el frontend
[[headers]]
  for = "/*"
  [headers.values]
    # CORS para desarrollo (si es necesario)
    Access-Control-Allow-Origin = "*"