# render.yaml - Con nueva contraseña y Transaction Pooler para producción
services:
  - type: web
    name: cartera-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm ci && npm run build
    startCommand: cd backend && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres.knditzgnblymqvmnmbmc:w3eEctJeKkBGhXuE@aws-0-us-east-1.pooler.supabase.com:6543/postgres
      - key: JWT_SECRET
        value: mi-super-clave-jwt-muy-segura-2024-cartera-barranquilla-produccion
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true
    rootDir: .